/*
 * This file was generated automatically by xsubpp version 1.9402 from the 
 * contents of Filesys.xs. Do not edit this file, edit Filesys.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Filesys.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include<sys/statvfs.h>
/* #include<string.h> */
#ifdef __cplusplus
}
#endif

typedef struct statvfs Statvfs;

XS(XS_Filesys__Statvfs_statvfs)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Filesys::Statvfs::statvfs(dir)");
    SP -= items;
    {
	char *	dir = (char *)SvPV(ST(0),na);
#line 21 "Filesys.xs"
	Statvfs st;
	Statvfs *st_ptr;
#line 23 "Filesys.xs"
#line 23 "Filesys.xs"
#line 24 "Filesys.xs"
	if(statvfs(dir, &st) == 0) {
		st_ptr=&st;
		EXTEND(sp, 15);
		PUSHs(sv_2mortal(newSViv(st_ptr->f_bsize)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_frsize)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_blocks)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_bfree)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_bavail)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_files)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_ffree)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_favail)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_fsid)));
		PUSHs(sv_2mortal(newSVpv(st_ptr->f_basetype, 0)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_flag)));
		PUSHs(sv_2mortal(newSViv(st_ptr->f_namemax)));
		PUSHs(sv_2mortal(newSVpv(st_ptr->f_fstr, 0)));
		/* HP-UX only 
		if(strcmp(OSNAME, "hpux") == 0) {
			PUSHs(sv_2mortal(newSViv(st_ptr->f_size))); 
			PUSHs(sv_2mortal(newSViv(st_ptr->f_time)));
		}
		*/
	}
	PUTBACK;
	return;
#line 46 "Filesys.xs"
#line 46 "Filesys.xs"
#line 46 "Filesys.xs"
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Filesys)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Filesys::Statvfs::statvfs", XS_Filesys__Statvfs_statvfs, file);
    ST(0) = &sv_yes;
    XSRETURN(1);
}
